DVA_TARGET_REQUEST_HEADER = "X-MGO-DVA-TARGET"
TARGET_URL_SIGNATURE_QUERY_PARAM = "mgo_signature"
FORWARD_URL_RESPONSE_HEADER = "X-MGO-PROXY-FORWARD-URL"
MEDMIJ_ACCESS_TOKEN_HEADER = "X-MGO-ACCESS-TOKEN"
