services:
    proxy:
        build:
            context: ./services/proxy
            dockerfile: docker/Dockerfile
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./services/proxy:/src
            - certs:/src/certs:ro
        depends_on:
            - certsmanager
            - mock
        ports:
            - 8001:8001
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mock:
        build:
            context: ./services/nl-mgo-dva-mock-private
            dockerfile: docker/Dockerfile
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        depends_on:
            - certsmanager
        ports:
            - 8002:443
        volumes:
            - ./services/nl-mgo-dva-mock-private:/src
            - certs:/src/certs:ro

    certsmanager:
        build:
            context: ./services/certsmanager
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - certs:/certs

    redis:
        image: redis:6.2
        depends_on:
            - certsmanager
        volumes:
            - certs:/src/certs:ro
        command: >
            redis-server
                --port 0
                --tls-port 6379
                --tls-cert-file /src/certs/out/redis-local.crt
                --tls-key-file /src/certs/out/redis-local.key
                --tls-ca-cert-file /src/certs/out/ca.crt
                --tls-auth-clients no
        restart: unless-stopped

    jaeger:
        image: jaegertracing/all-in-one:1.70.0
        ports:
        - "16686:16686"
        - "4317:4317"

volumes:
    certs:
