services:
    proxy:
        build:
            context: ./services/proxy
            dockerfile: docker/Dockerfile
            args:
                PROJECT_DIR: /src/services/proxy
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            ssh:
                - default
        environment:
            - JWE_KEY_PATH=./secrets/dva_target
            - JWT_SIGNING_KEY_PATH=./secrets/dva_target
        volumes:
            - .:/src
            - /src/services/proxy/.venv
            - certs:/src/services/proxy/certs:ro
        depends_on:
            - certsmanager
            - mock
            - redis
        ports:
            - 8001:8001
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mock:
        build:
            context: ./services/nl-mgo-dva-mock-private
            dockerfile: docker/Dockerfile
            args:
                PROJECT_DIR: /src/services/nl-mgo-dva-mock-private
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - .:/src
            - certs:/src/services/nl-mgo-dva-mock-private/certs:ro
        depends_on:
            - certsmanager
        ports:
            - 8002:443

    certsmanager:
        build:
            context: ./services/certsmanager
        volumes:
            - certs:/certs

    redis:
        image: redis:6.2
        volumes:
            - certs:/src/certs:ro
        depends_on:
            - certsmanager
        command: >
            redis-server
                --port 0
                --tls-port 6379
                --tls-cert-file /src/certs/out/redis-local.crt
                --tls-key-file /src/certs/out/redis-local.key
                --tls-ca-cert-file /src/certs/out/ca.crt
                --tls-auth-clients no
        restart: unless-stopped

    jaeger:
        image: cr.jaegertracing.io/jaegertracing/jaeger:2.15.1
        ports:
            - "16686:16686"
            - "4317:4317"

volumes:
    certs:
