name: "Setup app"
description: "Sets up UV for an application in a given directory."
inputs:
    app-dir:
        description: Path to Python application
        required: true
    github-token:
        description: GitHub token for accessing private dependencies
        required: true
runs:
    using: "composite"

    steps:
        - name: Setup Python environment with uv
          uses: astral-sh/setup-uv@v7
          with:
             enable-cache: true
             python-version: "3.11"

        - name: Install dependencies
          shell: bash
          working-directory: ${{ inputs.app-dir }}
          run: uv sync --locked
