from typing import Final


STATE_TOKEN_SEPARATOR: Final[str] = "\x1f"
STATE_TOKEN_CORRELATION_ID_INDEX: Final[int] = 0
STATE_TOKEN_TOKEN_ENDPOINT_URL_INDEX: Final[int] = 1
STATE_TOKEN_CLIENT_TARGET_URL_INDEX: Final[int] = 2
STATE_TOKEN_EXPIRATION_TIME_INDEX: Final[int] = 3
STATE_TOKEN_PART_COUNT: Final[int] = 4
