name: CI

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
            - develop
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

    lint:
        name: Run code linter
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

            - name: Lint
              working-directory: ./services/proxy
              run: uv run $(make lint --just-print --silent)

    format:
        name: Run formatter
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

            - name: Find format differences
              working-directory: ./services/proxy
              run: uv run $(make format-diff --just-print --silent)

    type-check:
        name: Check static types
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

            - name: Check static types
              working-directory: ./services/proxy
              run: uv run $(make type-check --just-print --silent)

    spelling-check:
        name: Run spelling check
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

            - name: Run spelling check
              working-directory: ./services/proxy
              run: uv run $(make spelling-check --just-print --silent)

    test:
        name: Run the tests
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup app
              uses: ./.github/actions/setup-app
              with:
                app-dir: ./services/proxy
                github-token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

            - name: Generate certificates
              working-directory: ./services/certsmanager
              run: CERTS_OUTPUT_DIR=../proxy/certs/out ./generate

            - name: Generate keys
              working-directory: ./services/proxy
              run: |
                uv run python tools/generate_oauth_state_signing_key.py secrets/oauth_state_signing_key.key --force
                uv run python tools/generate-key-pair.py --name=client_assertion_jwt
                uv run python tools/generate-key-pair.py --name=jwe --path=secrets/dva_target
                uv run python tools/generate-key-pair.py --type=ec --name=placeholder_jwt_signing --path=secrets/dva_target
                uv run python tools/generate-oidc-state-secret.py

            - name: Copy "app.conf.test" to "app.conf"
              working-directory: ./services/proxy
              run: cp app.conf.test app.conf

            - name: Run the tests
              working-directory: ./services/proxy
              run: uv run $(make test-cov-xml --just-print --silent)

            - name: Upload coverage report
              uses: actions/upload-artifact@v7
              if: always()
              with:
                name: coverage-proxy
                path: services/proxy/coverage.xml

    sonar:
        name: SonarCloud
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Download coverage report
              uses: actions/download-artifact@v8
              with:
                name: coverage-proxy
                path: services/proxy

            - name: Run SonarQube scan
              uses: minvws/action-sonarqube@v1
              with:
                sonar-token: ${{ secrets.SONAR_TOKEN }}
                project-base-dir: services/proxy
                allow-run-on-dependabot: 'true'
