name: Release package

on:
    push:
        tags:
            - v*

jobs:
    build-sources:
        runs-on: ubuntu-22.04
        env:
            PYTHON_VERSION: "3.11"

        steps:
            - uses: earthly/actions/setup-earthly@v1
              with:
                  version: v0.8.3

            - name: Checkout code
              uses: actions/checkout@v4

            - name: echo release version
              run: echo RELEASE_VERSION=$GITHUB_REF_NAME

            - name: Extract version from tag
              run: echo RELEASE_VERSION=$GITHUB_REF_NAME >> $GITHUB_ENV
              working-directory: ./services/proxy

            - name: Create release package
              run: |
                  earthly --ci --output +release-package \
                      --service=proxy \
                      --release_version=${{ env.RELEASE_VERSION }} \
                      --python_version=${{ env.PYTHON_VERSION }} \
                      --git_ref=${GITHUB_SHA}

            - name: Upload release package (source)
              uses: actions/upload-artifact@v4
              with:
                  name: dvp-proxy_${{ env.RELEASE_VERSION }}
                  path: ./dvp-proxy_${{ env.RELEASE_VERSION }}.tar.gz
                  if-no-files-found: error
