name: Package python virtual env

on:
  push:
    tags:
      - v*

jobs:
  build-venv:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build venv package
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/python-venv-package@main
        with:
          working_directory: './services/proxy'
          python_version: '3.11'
          package_file_name: 'dvp-proxy'
          checkout_repository: 'false'
